AppBundle\Entity\Test:
    type: entity
    table: test
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        test:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                default: WASUP
    lifecycleCallbacks: {  }
